### ISSUE TITLE
Dependency conflict

### ISSUE THREAD

**Issue by coldloaded** [Bombfuse/emerald#201] opened 2022-10-23 15:48 UTC
### Two versions of nix are causing this conflict, I guess ###   

 ...
   **Compiling nix v0.23.1
   Compiling nix v0.24.2**
   ...
   Compiling minimp3 v0.5.1
error[E0308]: mismatched types
   --> /home/pc/.cargo/registry/src/github.com-1ecc6299db9ec823/cpal-0.13.5/src/host/alsa/mod.rs:245:21
    |
244 |         let handle = match handle_result {
    |                            ------------- this expression has type `std::result::Result<host::alsa::alsa::PCM, (host::alsa::alsa::Error, host::alsa::alsa::nix::errno::Errno)>`
245 |             Err((_, nix::errno::Errno::EBUSY)) => return Err(BuildStreamError::DeviceNotAvailable),
    |                     ^^^^^^^^^^^^^^^^^^^^^^^^ expected enum `host::alsa::alsa::nix::errno::Errno`, found enum `nix::errno::Errno`
    |
    = note: perhaps two different versions of crate `nix` are being used?

error[E0308]: mismatched types
   --> /home/pc/.cargo/registry/src/github.com-1ecc6299db9ec823/cpal-0.13.5/src/host/alsa/mod.rs:246:21
    |
244 |         let handle = match handle_result {
    |                            ------------- this expression has type `std::result::Result<host::alsa::alsa::PCM, (host::alsa::alsa::Error, host::alsa::alsa::nix::errno::Errno)>`
245 |             Err((_, nix::errno::Errno::EBUSY)) => return Err(BuildStreamError::DeviceNotAvailable),
246 |             Err((_, nix::errno::Errno::EINVAL)) => return Err(BuildStreamError::InvalidArgument),
    |                     ^^^^^^^^^^^^^^^^^^^^^^^^^ expected enum `host::alsa::alsa::nix::errno::Errno`, found enum `nix::errno::Errno`
    |
    = note: perhaps two different versions of crate `nix` are being used?

error[E0308]: mismatched types
   --> /home/pc/.cargo/registry/src/github.com-1ecc6299db9ec823/cpal-0.13.5/src/host/alsa/mod.rs:302:21
    |
301 |         let handle = match handle_result {
    |                            ------------- this expression has type `std::result::Result<&mut host::alsa::alsa::PCM, (host::alsa::alsa::Error, host::alsa::alsa::nix::errno::Errno)>`
302 |             Err((_, nix::errno::Errno::ENOENT)) | Err((_, nix::errno::Errno::EBUSY)) => {
    |                     ^^^^^^^^^^^^^^^^^^^^^^^^^ expected enum `host::alsa::alsa::nix::errno::Errno`, found enum `nix::errno::Errno`
    |
    = note: perhaps two different versions of crate `nix` are being used?

error[E0308]: mismatched types
   --> /home/pc/.cargo/registry/src/github.com-1ecc6299db9ec823/cpal-0.13.5/src/host/alsa/mod.rs:302:59
    |
301 |         let handle = match handle_result {
    |                            ------------- this expression has type `std::result::Result<&mut host::alsa::alsa::PCM, (host::alsa::alsa::Error, host::alsa::alsa::nix::errno::Errno)>`
302 |             Err((_, nix::errno::Errno::ENOENT)) | Err((_, nix::errno::Errno::EBUSY)) => {
    |                                                           ^^^^^^^^^^^^^^^^^^^^^^^^ expected enum `host::alsa::alsa::nix::errno::Errno`, found enum `nix::errno::Errno`
    |
    = note: perhaps two different versions of crate `nix` are being used?

error[E0308]: mismatched types
   --> /home/pc/.cargo/registry/src/github.com-1ecc6299db9ec823/cpal-0.13.5/src/host/alsa/mod.rs:305:21
    |
301 |         let handle = match handle_result {
    |                            ------------- this expression has type `std::result::Result<&mut host::alsa::alsa::PCM, (host::alsa::alsa::Error, host::alsa::alsa::nix::errno::Errno)>`
...
305 |             Err((_, nix::errno::Errno::EINVAL)) => {
    |                     ^^^^^^^^^^^^^^^^^^^^^^^^^ expected enum `host::alsa::alsa::nix::errno::Errno`, found enum `nix::errno::Errno`
    |
    = note: perhaps two different versions of crate `nix` are being used?

error[E0308]: mismatched types
   --> /home/pc/.cargo/registry/src/github.com-1ecc6299db9ec823/cpal-0.13.5/src/host/alsa/mod.rs:720:36
    |
720 |         Err(err) if err.errno() == nix::errno::Errno::EPIPE => {
    |                                    ^^^^^^^^^^^^^^^^^^^^^^^^ expected enum `host::alsa::alsa::nix::errno::Errno`, found enum `nix::errno::Errno`
    |
    = note: perhaps two different versions of crate `nix` are being used?

   Compiling nalgebra v0.31.2
error[E0308]: mismatched types
   --> /home/pc/.cargo/registry/src/github.com-1ecc6299db9ec823/cpal-0.13.5/src/host/alsa/mod.rs:803:40
    |
803 |             Err(err) if err.errno() == nix::errno::Errno::EPIPE => {
    |                                        ^^^^^^^^^^^^^^^^^^^^^^^^ expected enum `host::alsa::alsa::nix::errno::Errno`, found enum `nix::errno::Errno`
    |
    = note: perhaps two different versions of crate `nix` are being used?

For more information about this error, try `rustc --explain E0308`.
error: could not compile `cpal` due to 7 previous errors
warning: build failed, waiting for other jobs to finish...

**Comment by Bombfuse** [comment] 2022-10-23 21:59
It looks like there's a version mismatch in dependencies, I'll try resolving this. I'm not sure how this made it through the github actions tests 🤔

**Comment by Bombfuse** [comment] 2022-10-23 22:01
Seems like both are sub-dependencies of kira. I don't think that we can fix this immediately, I'll need to include a Kira version update in the next big PR as part of the WGPU branch
![image](https://user-images.githubusercontent.com/26308406/197420206-759989bf-7508-438c-8dc2-653858854397.png)

**Comment by Bombfuse** [comment] 2022-10-23 22:48
Seems like this issue is triggering on the kira repo as well, I'm not sure what would cause this to break as it was working before.

https://github.com/tesselode/kira/actions/runs/3305051369/jobs/5454870747

**Comment by Bombfuse** [comment] 2022-10-24 18:27
confirmed upgrading our kira version will fix the issue, I should be able to do this after the WGPU migration is finished.

https://github.com/tesselode/kira/releases/tag/v0.7.1

**Comment by Bombfuse** [comment] 2022-11-09 01:59
hey @coldloaded I haven't updated Kira yet, however the WGPU branch has been merged into master.

 I tried WSL Ubuntu and I'm able to build successfully now, can you confirm on your end if the problem is resolved?

**Comment by coldloaded** [comment] 2022-11-09 04:05
yeah problem solved

**Closed** 2022-11-09 04:05 UTC
